spring:
  application:
    name: HikerTravelMapServer

  datasource:
    url: jdbc:postgresql://db-postgre-hiker.csqqgw7388qj.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: callee
    password: callee3124*
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG15Dialect
#        spatial:
#          database_function_schema: public